/**
 * generateSectorContent.js
 * Sector-level feature generation — anomaly zones, ruins, civilizations, hostile zones.
 *
 * Deterministic: same sector seed always produces the same content profile.
 * Pure function — no Firestore access.
 *
 * Uses a content seed derived from the sector seed so that these rolls are
 * fully isolated from the per-system / per-planet RNG sequence.
 *
 * Called by generateSector.js as a second RNG pass after system generation.
 */

import { createRng } from "./seededRandom.js";
import { generateSeed } from "./seedGenerator.js";

// ─── Sector-level anomaly types ───────────────────────────────────────────────

/** Sector-wide hazards (distinct from per-system anomalies in generateAnomaly.js). */
export const SECTOR_ANOMALY_TYPES = [
  "Subspace Distortion",
  "Temporal Anomaly",
  "Dark Matter Cloud",
  "Wormhole Fragment",
  "Energy Lifeform",
  "Nebula Interference",
];

// ─── Ancient ruins types ──────────────────────────────────────────────────────

/** Types of ruins or derelict structures that can be found in a sector. */
export const RUINS_TYPES = [
  "Ancient Alien Ruins",
  "Abandoned Station",
  "Derelict Starship",
  "Precursor Technology",
];

// ─── Feature probabilities ────────────────────────────────────────────────────

const ANOMALY_CHANCE     = 0.60;
const RUINS_CHANCE       = 0.35;
const CIVILIZATION_CHANCE = 0.25;
const HOSTILE_CHANCE     = 0.20;
const EMPTY_CHANCE       = 0.10;

// ─── Core function ────────────────────────────────────────────────────────────

/**
 * Generate sector-level content features from a deterministic seed.
 *
 * Each feature is an independent probability roll. A sector can have multiple
 * features simultaneously. `isEmptySector` is a gameplay signal that overrides
 * other features in presentation, but all rolls are still recorded.
 *
 * @param {number} sectorSeed  Numeric seed from sectorSeed() in seedGenerator.js
 * @returns {object}  Content profile — all fields stable for a given seed
 */
export function generateSectorContent(sectorSeed) {
  // Derive an isolated content seed — prevents interference with system/planet RNG
  const contentSeed = generateSeed(`${sectorSeed}:content`);
  const rng = createRng(contentSeed);

  const hasSectorAnomaly  = rng.next() < ANOMALY_CHANCE;
  const hasAncientRuins   = rng.next() < RUINS_CHANCE;
  const hasCivilization   = rng.next() < CIVILIZATION_CHANCE;
  const hasHostileZone    = rng.next() < HOSTILE_CHANCE;
  const isEmptySector     = rng.next() < EMPTY_CHANCE;

  return {
    // Sector-wide anomaly (not a per-system anomaly — a region-level hazard)
    hasSectorAnomaly,
    sectorAnomalyType: hasSectorAnomaly ? rng.pick(SECTOR_ANOMALY_TYPES) : null,

    // Ruins or derelict presence
    hasAncientRuins,
    ruinsType: hasAncientRuins ? rng.pick(RUINS_TYPES) : null,

    // Civilization indicator — actual civ data generated by firstContactEngine
    // when a first contact trigger is detected for a specific planet
    hasCivilization,

    // Hostile encounter zone — warns players before entering
    hasHostileZone,

    // Void designation — sector is largely empty of notable features
    // When true, gameplay should suppress other feature prompts
    isEmptySector,
  };
}
